name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONAN_HOME: /root/.conan2
  CCACHE_DIR: /data/ccache-data
  CCACHE_MAX_SIZE: '100G'
  CI_NUM_THREADS: "16"

jobs:
  build-test:
    runs-on: [ self-hosted, medium ]
    container: 
      image: bolt-registry:5000/bolt-ci:latest
      volumes:
        - /data/ccache-data:/data/ccache-data
    services:
      conanserver:
        image: bolt-registry:5000/conan-server:latest
        volumes:
          - /data/conan-server-data:/var/conan/data
    strategy:
      matrix: 
        build_type: [ release ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Add CI conan remote
      run: |
        source /root/venv/bin/activate
        conan remote add --index=0 ci http://conanserver:9300
      
    - name: Install Bolt dependencies
      run: |
        source /root/venv/bin/activate
        ./scripts/install-bolt-deps.sh

    - name: Bolt Build
      run: |
        source /root/venv/bin/activate
        make ${{ matrix.build_type }}_with_test

    - name: Run tests
      run: |
        source /root/venv/bin/activate
        make unittest_${{ matrix.build_type }}
